CREATE TABLE detail_karyawan(
  id int8 PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  nik VARCHAR(20),
  npwp VARCHAR(20),
  created_date timestamp NOT NULL,
  deleted_date timestamp NULL,
  updated_date timestamp NULL
);

CREATE TABLE karyawan (
  id int8 PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  nama varchar(50) NOT NULL,
  dob date not null,
  status varchar(20) not null,
  alamat text NULL,
  created_date timestamp NOT NULL,
  deleted_date timestamp NULL,
  updated_date timestamp NULL,
  detail_karyawan int8,
  FOREIGN KEY (detail_karyawan)
  	REFERENCES detail_karyawan (id)
);

CREATE TABLE rekening(
  id int8 PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  id_karyawan int8,
  nama VARCHAR(200),
  jenis VARCHAR(20),
  rekening VARCHAR(20),
  created_date timestamp NOT NULL,
  deleted_date timestamp NULL,
  updated_date timestamp NULL,
  FOREIGN key (id_karyawan)
  	REFERENCES karyawan (id)
);

CREATE TABLE training(
  id int8 PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  tema VARCHAR(50),
  pengajar VARCHAR(50),
  created_date timestamp NOT NULL,
  deleted_date timestamp NULL,
  updated_date timestamp NULL
);

CREATE TABLE karyawan_training(
  id int8 PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  id_karyawan int8,
  id_training int8,
  tanggal date,
  created_date timestamp NOT NULL,
  deleted_date timestamp NULL,
  updated_date timestamp NULL,
  FOREIGN KEY (id_karyawan)
  	REFERENCES karyawan (id),
  FOREIGN key (id_training)
  	REFERENCES training (id)
);